[package]
name = "prml-attestation"
version = "0.1.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"

[dependencies]
parity-codec = { version = "3.1", default-features = false, features = ["derive"] }
substrate-primitives = { path = "../../core/primitives", default-features = false }
sr-primitives = { package = "sr-primitives", path = "../../core/sr-primitives", default-features = false }
sr-std = { package = "sr-std", path = "../../core/sr-std", default-features = false }
sr-io = { package = "sr-io", path = "../../core/sr-io", default-features = false }
srml-support = { package="srml-support", path = "../../srml/support", default-features = false }
srml-system = { package = "srml-system", path = "../../srml/system", default-features = false }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"sr-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-system/std",
]
